name: OnlyHeroes
version: '${project.version}'
main: me.godnitze.onlyheroes.OnlyHeroes
api-version: 1.17
authors: [ Godnitze ]
description: A simple but original minigame.
commands:
  OnlyHeroes:
    description: Join a OnlyHero Game.
    usage: /<command>
    aliases: [oh, onlyh, oheroes]